### ISSUE TITLE
a conductor controller's view got disappeared

### ISSUE THREAD

**Issue by amoikevin** [zserge/anvil#109]
I use conductor togethor with anvil in my project.
here is my base Controller:
public abstract class BaseController extends Controller implements Anvil.Renderable
{
    @Override
    protected void onAttach(@NonNull View view) {
        super.onAttach(view);
        Anvil.mount(view, this);
    }

    @Override
    protected void onDetach(@NonNull View view) {
        super.onDetach(view);
        Anvil.unmount(view, false);
    }
}
and i have a home controller which use viewpager as its main content.
at first everything works well.buf after pressing the home button,and return back ,the viewpager's content disapears.

**Comment by amoikevin** [comment]
after upgrading to "commit 1da406d " ,now it works

**Comment by FunnyDevs** [comment]
I have same problem with conductor. I have created new RenderableView inside method 'onCreateView' of a Controller. When i push this new controller, the layout was build but, at the end of transition animations, it disappears.
