### ISSUE TITLE
Link in documentation 404's

### ISSUE THREAD

**Issue by dlmiddlecote** [zserge/anvil#12]
Just a note;
This link 'full list of available generators to bind data and listeners to your views' in the Documentation isn't found.

Thanks,
Dan.

**Comment by zserge** [comment]
Ah, correct. Thanks for reporting! In fact I removed that markdown document in favor of JavaDocs, just forgot about the reference.
Do you know any good places to host the JavaDocs (something like godoc.org for the Go language)? It would be nice to publish Anvil docs somewhere and place a link to that place in the readme.

**Comment by dlmiddlecote** [comment]
I'm not entirely sure, sorry! You could make a anvil.github.io and host the generated JavaDocs there?

**Comment by dlmiddlecote** [comment]
Or a zserge.github.io/anvil site, to be more precise.

**Comment by zserge** [comment]
@dlmiddlecote Wandering around the github projects I found that one has links to JavaDocs right to the sonatype website. I adjusted their URL and got Anvil documentation working as well!

So now README contains links to the full java docs and to the generators (data binding methods).
