### ISSUE TITLE
Rerendering list item in RenderableArrayAdapter

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#18]
It seems that individual item views in a `RenderableArrayAdapter` are only rerendered when they scroll off/on the screen.

Basically, I have a list of questions that can be selected by the user. Questions that have been answered already are in one color, the current selected question is in another, and questions to be answered are in a third.

Right now, when a question is selected no change occurs in its view within the `RenderableArrayAdapter`. It only changes to the selected color when I've scrolled it off/on the screen. I'd like to either be able to force a re-render when the question is clicked, or (even better) have Anvil re-render all the visible cells as part of the Anvil.render() cycle. Is there any reason why this isn't the case?

**Comment by zserge** [comment]
It makes sense. Anvil.render() should update all visible adapter items.
I wonder if adding `notifyDataSetChanged()` to the RenderableAdapter `view()` helps?

**Comment by corbt** [comment]
I can confirm that manually calling `notifyDataSetChanged()` on the `RenderableAdapter` when a rerendering is necessary causes it to behave correctly.

**Comment by corbt** [comment]
I can also confirm that calling it from RenderableAdapter's `view()` does not work, unfortunately. Is there any function called on RenderableAdapter every time the page is rerendered? It feels like `view` would be that function, but as far as I can tell it's never actually called.

**Comment by zserge** [comment]
I've just added it in the recent commit

**Comment by corbt** [comment]
Have you confirmed that that commit works? I've tested the same change locally and the `view` function appears to never be called.

**Comment by zserge** [comment]
Oops.

**Comment by zserge** [comment]
It doesn't work because Anvil keeps one list of renderables and their mounts, while adapter keep another one internally for its child items.

If RenderableAdapter was added to the Anvil.mounts set - it would have been updated on the next render cycle and calling notifyDataSetChanged from inside view() would work. 

To add a Renderable to the mounts set one can just call Anvil.render(r) with that specific renderable. However I'm afraid Anvil will crash since view() returns null. Adding a null check to the Anvil.render() might fix it. Sorry, I can't test it right now.

**Comment by zserge** [comment]
Ok, I'll probably close this. In the new Anvil the adapters don't render themselves when Anvil.render() is called and I think it's a correct approach:

1) If you really want to update your adapter every time the view is rendered - just add `notifyDataSetChanged()` in your `view()` method or into any other renderable holding your listview. Then whenever the listview is re-rendered - the adapter items are updated, too
2) If you want to gain some performance - explicitly call notifyDataSetChanged when your adapter data is changed and Anvil.render() in all other cases.
