### ISSUE TITLE
Finally a React like library for Android

### ISSUE THREAD

**Issue by frostymarvelous** [zserge/anvil#22]
This is the react I have been looking for for my [Flux](https://github.com/frostymarvelous/DroidFlux).

**Comment by zserge** [comment]
Wow! And I have been thinking about bringing Flux architecture to android+Anvil somehow: https://github.com/zserge/anvil/issues/7#issuecomment-90494380
I will definitely look at DroidFlux.

Btw, if you want to submit an example of DroidFlux+Anvil - please do a pull request to zserge/anvil-examples repo!

**Comment by frostymarvelous** [comment]
I will do so. Still wrapping my head around Anvil and finishing up DroidFlux in the interim as well.
