### ISSUE TITLE
Anvil renders views in background activities

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#23]
As I've been writing more Anvil views (I haven't counted, but my project now currently has several thousand lines of Anvil split between about a dozen views), I'm beginning to run into performance issues.

One problem is that Anvil continues rendering all views even when they're in the background. Specifically, the starting activity of my project has a quite expensive view (it requires loading many images from disk). Every time Anvil re-renders on any page I've noticed that it re-renders that view as well.

I need to optimize that view so it doesn't keep repeating (and that's my first step), but would it be possible for Anvil to only re-render views that are in the current activity/are currently visible?

**Comment by zserge** [comment]
Anvil keeps a list of weak references to Renderables. Once GC collects your background activity - the views inside it should not be rendered anymore.

Adding some kind of `Anvil.remove(renderable)` could be helpful to make it explicitly. You may look at Anvil class, there is a set of mounts. Adding a method to remove your component from that set would avoid rendering it on the next call of `Anvil.render()`. If this fixes some of your performance issues - then pull requests are welcome :)

**Comment by zserge** [comment]
Old Anvil (0.0.12) used adapters via some kind of a hack, so one had to call `notifyDataSetChanged()` every time the parent view was re-rendered.

New Anvil uses ViewHolder pattern, and adapter views are reactive, so they are updated even without notifyDataSetChanged, automatically. So I will close this one I merge anvil-forge with the master branch.

**Comment by zserge** [comment]
Closing this, since new Anvil allows to explicitly unmount renderables (as well as to let them be GC'ed). So this issue should be fixed by now.
