### ISSUE TITLE
Upgrading 0.0.12 to 0.1.2 -- config equivalent?

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#30]
I'm very excited about the changes you've made in the 0.1 release! I just got around to updating my dependency now, and in the last hour I've been working on updating to the new DSL. The migration has been very straightforward, given how much Anvil has changed on the inside! I've already been able to update all my custom attributes and about half of my views. Most of it has been an easy, mechanical, copy-paste type process, which is nice. :)

However, I'm not sure how to get ahold of the underlying view to perform the equivalent of the `config` option from 0.0.12, which seems to be missing. Is there a way to make that work? Thanks.

**Comment by zserge** [comment]
Hi, @corbt! Glad to hear your interest to Anvil is back :)

As you might remember the old Anvil's `config()` was needed only to get access to the real view object.
In the new Anvil you always have access to the real view object inside your renderable lambdas. Just call `Anvil.currentView()` and you will get the view instance which is currently being modified, e.g.:

``` kotlin
linearLayout {
  val layout = (LinearLayout) Anvil.currentView();
  // Here you may use real LinearLayout instance
  button {
     if (!myButtonIsInitialized) {
        // Get real Button instance
        val b = (Button) Anvil.currentView();
        initializeMyButton(b);
        myButtonIsInitialized = true;
     }
     text("Click me")
     onClick { v -> ... }
     ....
  }
}
```

The only catch here is that the first rendering cycle may happen to early and if you want, say, to get view width in pixels - it will return zero. So you may force rendering to be done in a loop again and again until view width becomes a valid number:

``` java
int mWidth = -1;
...
frameLayout(() -> {
  if (mWidth <= 0) {
    if ((mWidth = Anvil.currentView().getWidth()) == 0) {
      post(Anvil::render);
    }
  }
});
```

**Comment by corbt** [comment]
Ok, sounds good. A related question: often I want to call a function on the view only on the first render (which was a property of the `config` attribute). I suppose I could use a sentinel boolean to mark when my code has been run once and skip it after that, but is there a way to get this behavior built into the framework? If not I guess I'll just create my own `config` that implements that behavior. :)

**Comment by zserge** [comment]
Sorry, at the moment sentinel boolean is the only solution. I'm still not sure if a function like `config` is really needed in Anvil core. I expect most of the UI to be controlled in a declarative manner via Anvil DSL, so `config` is rather an exception.

I would implement config as `config(cb: () -> Boolean)` that would execute cb and re-schedule Anvil.render until the cb returns true. In simple cases it would run it once, in more complex it will stop once view is initialized. But such implementation would require to keep a flag variable bound to the view, which implies using a WeakHashMap etc. This generic solution can quickly become complicated for a small library like Anvil.

So I suggest writing `config`-like wrappers manually for now, unless we see that every Anvil user does it and their implementations look very similar. Then it would be wise to have a generic implementation added to the Anvil core.

**Comment by corbt** [comment]
Ok. I suspect that this will be a useful/commonly-requested function, but if you want to leave it out until more people request it that's fine with me. I've included my implementation below so if anyone else needs this functionality they can copy it into their project.

```java
public interface ConfigListener {
    abstract public void config(View v);
}

public static void config(final ConfigListener listener) {
    attr(configFunc.instance, listener);
}

private final static class configFunc implements Anvil.AttrFunc<ConfigListener> {
    private final static configFunc instance = new configFunc();
    @Override
    public void apply(View view, ConfigListener listener, ConfigListener old) {
        if(old == null)
            listener.config(view);
    }
}
```

**Comment by zserge** [comment]
Ok, Anvil 0.2.0 is here, it includes the 'init' function that runs the attached lambda only once, like:

```
textView {
  init {
    val tv: TextView = Anvil.currentView()
    tv.setText("hello");
  }
}
```

It follows the code you've submitted, just renamed it to 'init' since it seems to be more precise (initialization happens once for sure, while configuration may happen many times).
