### ISSUE TITLE
Support library v4 bindings

### ISSUE THREAD

**Issue by zserge** [zserge/anvil#33]
I scanned support v4 JAR and got a list of all view classes and their public
setters.

A hand-written library "anvil-support-v4" should be written to handle these
cases. Method names should not conflict with the ones from DSL.java.

Below is a list of all classes and their methods that Anvil should (and should
not) support.

Any comments are welcome!

## Anvil should support

	android.support.v4.view.ViewPager
		addFocusables(ArrayList,int,int)
		addOnPageChangeListener(ViewPager$OnPageChangeListener)
		addTouchables(ArrayList)
		setAdapter(PagerAdapter)
		setCurrentItem(int)
		setCurrentItem(int,boolean)
		setOffscreenPageLimit(int)
		setOnPageChangeListener(ViewPager$OnPageChangeListener)
		setPageMargin(int)
		setPageMarginDrawable(Drawable)
		setPageMarginDrawable(int)
		setPageTransformer(boolean,ViewPager$PageTransformer)

	android.support.v4.widget.DrawerLayout
		addFocusables(ArrayList,int,int)
		setChildInsets(Object,boolean)
		setDrawerElevation(float)
		setDrawerListener(DrawerLayout$DrawerListener)
		setDrawerLockMode(int)
		setDrawerLockMode(int,View)
		setDrawerLockMode(int,int)
		setDrawerShadow(Drawable,int)
		setDrawerShadow(int,int)
		setDrawerTitle(int,CharSequence)
		setScrimColor(int)
		setStatusBarBackground(Drawable)
		setStatusBarBackground(int)
		setStatusBarBackgroundColor(int)

	android.support.v4.widget.SlidingPaneLayout
		setCoveredFadeColor(int)
		setPanelSlideListener(SlidingPaneLayout$PanelSlideListener)
		setParallaxDistance(int)
		setShadowDrawable(Drawable)
		setShadowDrawableLeft(Drawable)
		setShadowDrawableRight(Drawable)
		setShadowResource(int)
		setShadowResourceLeft(int)
		setShadowResourceRight(int)
		setSliderFadeColor(int)

	android.support.v4.widget.SwipeRefreshLayout
		setColorScheme(int[])
		setColorSchemeColors(int[])
		setColorSchemeResources(int[])
		setDistanceToTriggerSync(int)
		setNestedScrollingEnabled(boolean)
		setOnRefreshListener(SwipeRefreshLayout$OnRefreshListener)
		setProgressBackgroundColor(int)
		setProgressBackgroundColorSchemeColor(int)
		setProgressBackgroundColorSchemeResource(int)
		setProgressViewEndTarget(boolean,int)
		setProgressViewOffset(boolean,int,int)
		setRefreshing(boolean)
		setSize(int)

## Anvil should not support

	- FragmentTabHost (it's normally inflated from XML and has no data bindings
	  nor dynamic styles, so there is no benefit from using Anvil bindings)
	- PagerTabStrip - also, inflated from XML and has no dynamic behaviour
	- PagerTitleStrip - see PagerTabStrip
	- NestedScrollView - it's rarely used, and it has a large/complex API
	- Space - a normal View class can be used as well in most cases

**Comment by tilal6991** [comment]
Can be closed I think.

**Comment by zserge** [comment]
Yep, the pull request covered even more than planned here.
