### ISSUE TITLE
Support library v7 bindings

### ISSUE THREAD

**Issue by zserge** [zserge/anvil#34]
Android Support library v7 includes several components: appcompat, grid,
cardview, recyclerview and palette.

Palette is of little interest to Anvil since it contains no View classes.

CardView, Grid and RecyclerView contain one view each + all the classes to work
with that view.

AppCompat contains a number of typical views from Android SDK wrapped with
slightly enhanced functionality and changed look-and-feel.

I expect Anvil to support all views listed in the support libraries and provide bindings for the most typical methods.

## AppCompat Views

	AppCompat.autoCompleteTextView()
		setDropDownBackgroundResource(int)
	AppCompat.button()
	AppCompat.checkBox()
	AppCompat.checkedTextView()
	AppCompat.editText()
	AppCompat.multiAutoCompleteTextView()
	AppCompat.radioButton()
	AppCompat.ratingBar()
	AppCompat.spinner()
	AppCompat.textView()
	AppCompat.linearLayout()
	AppCompat.searchView()
	AppCompat.switch()
		setChecked(boolean)
		setShowText(boolean)
		setSplitTrack(boolean)
		setSwitchMinWidth(int)
		setSwitchPadding(int)
		setSwitchTextAppearance(android.content.Context,int)
		setSwitchTypeface(android.graphics.Typeface)
		setSwitchTypeface(android.graphics.Typeface,int)
		setTextOff(java.lang.CharSequence)
		setTextOn(java.lang.CharSequence)
		setThumbDrawable(android.graphics.drawable.Drawable)
		setThumbResource(int)
		setThumbTextPadding(int)
		setTrackDrawable(android.graphics.drawable.Drawable)
		setTrackResource(int)
	AppCompat.toolbar()
		setCollapsible(boolean)
		setContentInsetsAbsolute(int,int)
		setContentInsetsRelative(int,int)
		setLogo(android.graphics.drawable.Drawable)
		setLogo(int)
		setLogoDescription(int)
		setLogoDescription(java.lang.CharSequence)
		setMenu(internal.view.menu.MenuBuilder,ActionMenuPresenter)
		setMenuCallbacks(MenuPresenter$Callback,MenuBuilder$Callback)
		setNavigationContentDescription(int)
		setNavigationContentDescription(java.lang.CharSequence)
		setNavigationIcon(android.graphics.drawable.Drawable)
		setNavigationIcon(int)
		setNavigationOnClickListener(android.view.View$OnClickListener)
		setOnMenuItemClickListener(Toolbar$OnMenuItemClickListener)
		setOverflowIcon(android.graphics.drawable.Drawable)
		setPopupTheme(int)
		setSubtitle(int)
		setSubtitle(java.lang.CharSequence)
		setSubtitleTextAppearance(Context,int)
		setSubtitleTextColor(int)
		setTitle(int)
		setTitle(java.lang.CharSequence)
		setTitleTextAppearance(Context,int)
		setTitleTextColor(int)

	AppCompat.actionMenu()
		setExpandedActionViewsExclusive(boolean)
		setMenuCallbacks(MenuPresenter$Callback,MenuBuilder$Callback)
		setOnMenuItemClickListener(ActionMenuView$OnMenuItemClickListener)
		setOverflowIcon(Drawable)
		setOverflowReserved(boolean)
		setPopupTheme(int)
		setPresenter(ActionMenuPresenter)

## AppCompat methods

For all tintable views:

	setSupportAllCaps(boolean)
	setSupportBackgroundTintList(android.content.res.ColorStateList)
	setSupportBackgroundTintMode(android.graphics.PorterDuff$Mode)

## Card views and methods
	
	Card.card() to create android.support.v7.widget.CardView

		setRadius(float)
		setShadowPadding(int,int,int,int)
		setPadding(int,int,int,int)
		setPaddingRelative(int,int,int,int)
		setUseCompatPadding(boolean)
		setContentPadding(int,int,int,int)
		setCardBackgroundColor(int)
		setCardElevation(float)
		setMaxCardElevation(float)
		setPreventCornerOverlap(boolean)

## Grid views and methods

	Grid.grid()
		setOrientation(int)
		setRowCount(int)
		setColumnCount(int)
		setUseDefaultMargins(boolean)
		setAlignmentMode(int)
		setRowOrderPreserved(boolean)
		setColumnOrderPreserved(boolean)
		setPrinter(android.util.Printer)

## Recycler views and methods

	Recycler.recyclerView()
		addFocusables(java.util.ArrayList,int,int)
		addItemDecoration(RecyclerView$ItemDecoration)
		addItemDecoration(RecyclerView$ItemDecoration,int)
		addOnChildAttachStateChangeListener(RecyclerView$OnChildAttachStateChangeListener)
		addOnItemTouchListener(RecyclerView$OnItemTouchListener)
		addOnScrollListener(RecyclerView$OnScrollListener)

		setAccessibilityDelegateCompat(RecyclerViewAccessibilityDelegate)
		setAdapter(RecyclerView$Adapter)
		setChildDrawingOrderCallback(RecyclerView$ChildDrawingOrderCallback)
		setClipToPadding(boolean)
		setHasFixedSize(boolean)
		setItemAnimator(RecyclerView$ItemAnimator)
		setItemViewCacheSize(int)
		setLayoutFrozen(boolean)
		setLayoutManager(RecyclerView$LayoutManager)
		setNestedScrollingEnabled(boolean)
		setOnScrollListener(RecyclerView$OnScrollListener)
		setRecycledViewPool(RecyclerView$RecycledViewPool)
		setRecyclerListener(RecyclerView$RecyclerListener)
		setScrollingTouchSlop(int)
		setViewCacheExtension(RecyclerView$ViewCacheExtension)

**Comment by zserge** [comment]
See https://github.com/trikita/anvil-recyclerview for the implementation of a RecyclerView bindings

**Comment by tilal6991** [comment]
AppCompat and Design are done. The others would require more thought than just generating bindings - something along the lines of what you've done with recycler view would be in order.

**Comment by zserge** [comment]
Since grid, card and recyclerview bindings are done - I think we can close this.
