### ISSUE TITLE
Show gradle dependency in README

### ISSUE THREAD

**Issue by samtstern** [zserge/anvil#36]
I had to read the source to figure out the dependency line is:
```
compile 'co.trikita:anvil:0.1.2'
```

**Comment by zserge** [comment]
Actually, I don't think it's correct.

Previously, Anvil library contained renderer core and DSL for API levels 10 (Android 2.3) and 15 (Andorid 4.0) in a single bundle. And it was available as 'co.trikita:anvil:0.0.12'.

Current Anvil has core and DSL split in two gradle modules, DSL has a dependency on the core. So in your project you should include DSL as a dependency (e.g. 'co.trikita:anvil-sdk15:+' as said in the README). This, in its turn would also fetch 'co.trikita:anvil:0.1.2' which is renderer core and is of little use on its own without DSL.

Can you still build your project just specifying 'co.trikita:anvil-sdk15:0.1.2' as a dependency, like README says? If not - what kind of errors do you get?

**Comment by samtstern** [comment]
Ah sorry you are right, I totally missed the section at the end of the README.  I would suggest putting it at the top, but that's a matter of opinion.

Also this is what the README says:
```
 compile 'co.trikita:anvil-api15:+'
```

I think that should be `anvil-sdk15` and not `anvil-api15

**Comment by zserge** [comment]
Oh, that's my fault. I was thinking about `api15` vs `sdk15`, ended up with `sdk15`, but missed that in readme. Fixed now.

**Comment by samtstern** [comment]
Awesome, thanks!

**Comment by bj0** [comment]
It might also help to mention installing the support libraries in the README.
