### ISSUE TITLE
Anvil needs a logo

### ISSUE THREAD

**Issue by zserge** [zserge/anvil#47]
Every great library should have an eye-catching logo. @krugloid, any ideas?

**Comment by krugloid** [comment]
I think of it as of an A-shaped rocket. Anvil starts with a letter "A". As well as rockets, Anvil is related to reactivity. It helps to create reactive views.
Attaching logo and Android launcher icon (for Anvil examples) below.

<img src="https://raw.githubusercontent.com/zserge/anvil/master/logo/logo.png" alt="logo" width="96px" height="96px" /><img src="https://raw.githubusercontent.com/zserge/anvil/master/logo/ic_launcher.png" alt="Android launcher icon" width="96px" height="96px" />

Please, tell me you like it ;)

**Comment by zserge** [comment]
:+1: :clap: Love the colors and the minimal style, also it resembles Java Duke a little. Shall we put it into the readme?

**Comment by zeapo** [comment]
:+1:
