### ISSUE TITLE
Problems with import of anvil Methods

### ISSUE THREAD

**Issue by BenedictP** [zserge/anvil#51]
**First example:**
When I try to import the xml Method with Android-Studio:

<img width="369" alt="screen shot 2016-04-07 at 15 43 45" src="https://cloud.githubusercontent.com/assets/5817002/14353045/9944ffde-fcd7-11e5-9e2b-49fc9e263473.png">

This happens:

<img width="371" alt="screen shot 2016-04-07 at 15 44 39" src="https://cloud.githubusercontent.com/assets/5817002/14353058/b34ea02e-fcd7-11e5-9776-1966fcc4c92e.png">

I need to manually add `import trikita.anvil.DSL.xml`

**Second example:**

<img width="427" alt="screen shot 2016-04-07 at 15 50 21" src="https://cloud.githubusercontent.com/assets/5817002/14353230/779daa9c-fcd8-11e5-906f-98c550a27a58.png">

When I add `import trikita.anvil.DSL.backgroundColor` it works.

I'm using Android-Studio 1.5.1 with Kotlin 1.0.0 and anvil-sdk15:0.3.1.

**Comment by zserge** [comment]
Studio is known to put or suggest wrong imports. I just read the rants on Reddit about java.sql.Date import vs java.util.Date (Studio forces the first one).

I personally use DSL class by writing a wildcard static import manually:

```
import static trikita.anvil.DSL.*;
```

**Comment by BenedictP** [comment]
For beginners this could be a little bit unclear.
My first reaction was to check the build.gradle if I'm missing something ;)

**Comment by zserge** [comment]
@BenedictP Totally agree, and that's what readmes are for ;) https://github.com/zserge/anvil/blame/master/README.md#L61
