### ISSUE TITLE
Use of singletons in view bindings

### ISSUE THREAD

**Issue by tilal6991** [zserge/anvil#58]
In all the generated attribute application functions, a corresponding singleton is generated. Unfortunately, across the 4 projects there are now hundreds of these and _all_ are intialised on startup of the app. This is extremely expensive to say the least and is especially bad considering many of them are quite obscure and would never be used.

I propose to turn them into lazy singletons instead which would ensure that only the functions required would be cached.

**Comment by tilal6991** [comment]
(P.S. @zserge would it be possible to chat about the future of this project and related ones (Bansa/Redux) - IRC maybe? @brianegan too)

**Comment by brianegan** [comment]
I'd be up for chatting more about it! Perhaps we could put together a small slack channel or something?

**Comment by zserge** [comment]
Anvil has a Gitter room - feel free to join: https://gitter.im/zserge/anvil

**Comment by zserge** [comment]
I've recently rewritten all DSLs and there is no more lambas (pull request #99), each DSL is just one class, so it's safe to close this issue.
