### ISSUE TITLE
Using tree packages of anvil

### ISSUE THREAD

**Issue by carloslfu** [zserge/anvil#64]
Hello, I'm starting to use Anvil and porting an existing app that use XML only. I need to use anvil-appcompat-v7, anvil-design and anvil-sdk15 packages, I have added the next code to gradle:

``` gradle
compile 'co.trikita:anvil-sdk15:0.2.0'
compile 'co.trikita:anvil-design:0.3.4'
compile 'co.trikita:anvil-appcompat-v7:0.3.4'
```

But, building throws this error: `Error: more than one library with package name 'trikita.anvil'`, I'm doing it in the wrong way?

**Comment by tilal6991** [comment]
Currently the Anvil artefacts are a little bit broken since they do not have the latest fixes to deal with the clashing package names.

Ping @zserge - please update them :)

**Comment by zserge** [comment]
@carloslfu Published Anvil 0.3.5 with the support libraries included and having separate packages.

@tilal6991 Sorry, 0.4.0 will be released once we add recyclerview-v7 and thus finalize the support libraries in Anvil.

**Comment by tilal6991** [comment]
No need to apologise - the version number doesn't matter as long as there's some version out which works :)

**Comment by carloslfu** [comment]
Thanks @zserge .
