### ISSUE TITLE
not able to set adapter for RenderableRecyclerViewAdapter

### ISSUE THREAD

**Issue by devangazoi** [zserge/anvil#72]
Hello Folks,
I have tried to set adapter for RenderableRecyclerViewAdapter but getting below error.
Error:(65, 28) error: no suitable method found for adapter(RenderableRecyclerViewAdapter)
method DSL.adapter(Adapter) is not applicable
(argument mismatch; RenderableRecyclerViewAdapter cannot be converted to Adapter)
method DSL.adapter(ExpandableListAdapter) is not applicable
(argument mismatch; RenderableRecyclerViewAdapter cannot be converted to ExpandableListAdapter)

Please suggest me how to resolve this error.

I have included below lines in build.gradle.
  compile 'co.trikita:anvil-sdk15:0.4.0'
  compile 'co.trikita:anvil-recyclerview-v7:0.4.0'
  compile 'com.android.support:recyclerview-v7:23.0.1' 

Looking forward for your response.

Thanks,
Devang

**Comment by devangazoi** [comment]
Resolved by using below adapter.
trikita.anvil.recyclerview.v7.RecyclerViewv7DSL.adapter

code:
layoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
hasFixedSize(true);
itemAnimator(new DefaultItemAnimator());
adapter(renderableRecyclerViewAdapter);

Thanks,
Devang

**Comment by zserge** [comment]
@devangazoi Exactly, that's an unfortunate limitation of Anvil's Java DSL. For non-standard (e.g. support) views and method you have to specify the "namespace" (the corresponding DSL class name) explicitly like you did.

**Comment by devangazoi** [comment]
Hello Folks,

I would like to know that how to handle "onclick" and onlongclick for RecyclerView items. For that, I have checked all methods of RecyclerViewv7DSL but seems there is not any method for same.

I have also tried to handle onclick and onlongclick using DSL but its not working.

Please help me to resolve it and meanwhile also trying to resolve it.

Thanks,
Devang

**Comment by zserge** [comment]
@devangazoi You mean similar to onItemClick in ListViews? Inside recycler view you have to handle that for each item individually, e.g. inside your adapter:

```
RenderableRecyclerViewAdapter adapter = RenderableRecyclerViewAdapter.withItems(myList, (index, item) -> {
  linearLayout(() -> {
     ...
     onClick(v -> {
       // "v" is a view user clicked on, "index" and "item" refer to the corresponding data item
     });
  });
});
```

**Comment by devangazoi** [comment]
Thanks you very much for your quick response. Now it working fine.

Regards,
Devang
