### ISSUE TITLE
How can I set a custom attribute like R.attr.fontPath?

### ISSUE THREAD

**Issue by wellguimaraes** [zserge/anvil#76]
How can I set a custom attribute like R.attr.fontPath?

**Comment by zserge** [comment]
@wellguimaraes Custom attributes normally come with custom views, thus to set them you will need to call a custom method of a custom view. Anvil allows you to call view methods directly, so if your view setter is `setFontPath` or something like that then you should be able to do something like:

```
someView(() -> {
  init(() -> {
    SomeView v = Anvil.currentView();
    v.setFontPath(R.attr.fontPath);
  });
});
```

Anvil knows nothing about XMLs and hidden magic behind those, but all XML attributes end up in Java code anyway. Which means as long as you know how to control/configure your views from Java - it would be no different with Anvil. 

Alternatively, you may still use XMLs for layouts and Anvil for data binding (see Anvil's `xml()` method).
