### ISSUE TITLE
Use Android Complex Units

### ISSUE THREAD

**Issue by ElectricCookie** [zserge/anvil#80]
Since Anvil only uses pixes to set properties such as padding or margin, it would be nice to have the option to use units like dp,dip,sp etc. 
Something like: 

```java

 DSL.linearLayout(() -> {

    DSL.orientation(LinearLayout.VERTICAL);
    DSl.padding(DSL.DP,15));

});

```

**Comment by danhawkes** [comment]
There's actually BaseDSL.dip() and sip() for this already.

**Comment by ElectricCookie** [comment]
Oh nice. Thanks!
