### ISSUE TITLE
AppCompatCheckBox checked method

### ISSUE THREAD

**Issue by gnardini** [zserge/anvil#84]
Thanks for all the hard work you put in, the library is great.

Today I run into a problem. It might just be me misunderstanding something, but I have the following code:

``` kotlin
    AppCompatv7DSL.appCompatCheckBox {
        /* other stuff */
        checked(item.selected)
    }
```

This is not working The checkbox doesn't change it's state. The way I found to get it to work and set the checkbox to its correct state is:

``` kotlin
    AppCompatv7DSL.appCompatCheckBox {
        /* other stuff */
        val checkbox = Anvil.currentView<AppCompatCheckBox>()
        checkbox.isChecked = item.selected       
    }
```

**Comment by zserge** [comment]
@gnardini We have rewritten our attribute dispatch mechanism, now name clashes (such as `checked()` in support DSL and `checked()` in normal SDK DSL) get resolved nicely. I've tried the following view code and got it working with the Anvil from master branch:

```java
    private class TestCheckBox extends RenderableView {
        private boolean selected;
        public TestCheckBox(Context c) { super(c); }
        public void view() {
            linearLayout(() -> {
                button(() -> {
                    onClick(v -> selected = !selected);
                });
                appCompatCheckBox(() -> {
                    checked(selected);
                });
            });
        }
    }
```

**Comment by gnardini** [comment]
Thanks for looking into it!
