### ISSUE TITLE
Custom View in XML Layout

### ISSUE THREAD

**Issue by mitchryanjusay** [zserge/anvil#86]
I'm using ViewPagerIndicator in an XML layout and am trying to set its ViewPager in the RenderableView via ID but since it's a custom view I cannot access its methods within the DSL. So far the only guides I've seen are for declaring custom views in the DSL but not for referencing from IDs in the XML. Is this possible or do I have to manually do what I need to get done?

**Comment by niltonvasques** [comment]
Hi, I think that you can use something like this:
```java
xml(R.layout.content, () -> {
            withId(R.id.view_pager_indicator, () -> {
                ViewPagerIndicator indicator = (ViewPagerIndicator) Anvil.getCurrentView();
                  //You can access any ViewPagerIndicator methods
            });
        });
    });
```
