### ISSUE TITLE
It's is possible to know when the Anvil render method was finished?

### ISSUE THREAD

**Issue by niltonvasques** [zserge/anvil#87]
This would be useful for UI automated tests, because is common to wait for UI rendering before run assertions.

**Comment by zserge** [comment]
`Anvil.render()` is synchronous when called from the UI thread.
It uses main thread handler when called from the background threads, so you may need to use `runOnUiThead()` or another UI thread handler in your tests to ensure that `Anvil.render()` runs synchronously.

**Comment by niltonvasques** [comment]
Thanks @zserge. Currently we are using exactly the solution proposed by you, and keeping a callback in UI Components to notify listeners when the render finishs.

**Comment by niltonvasques** [comment]
I will close that since the solution is enough!
