### ISSUE TITLE
Example for anvil 0.4+ with RecyclerView

### ISSUE THREAD

**Issue by rubiktubik** [zserge/anvil#89]
I'am try to use the 0.4.0 version of the anvil library with the recycler view.
Which was promoted on [link](http://zserge.com/blog/anvil-support-libraries.html)

And i have problems to get it to work properly. Because i get errors from Android Studio.

I created a class which represents my layout:
`public class TimerLayout extends RenderableView`

Then in the view method i use the anvil DSL.

```Java
public void view() {
        linearLayout(() -> {
            orientation(LinearLayout.VERTICAL);


            textView(() -> {
                size(MATCH, WRAP);
                text("Hello");
            });
...
````

Everythings works fine until i try to use the recyclerView:

```Java
recyclerView(() -> {
                linearLayoutManager();
                adapter(recycleAdapter);
            });
```
Then i get the following error:
![error](https://cloud.githubusercontent.com/assets/115047/20194398/6fc31f7c-a792-11e6-8cba-e683483df242.PNG)

In gradle i imported the following dependencies:
```gradle
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'
    compile 'com.github.trikita:jedux:-SNAPSHOT'
    compile 'co.trikita:anvil-sdk15:0.4.0'
    compile 'co.trikita:anvil-support-v4:0.4.0'
    compile 'co.trikita:anvil-recyclerview-v7:0.4.0'
    compile 'co.trikita:anvil-cardview-v7:0.4.0'
    compile 'co.trikita:anvil-appcompat-v7:0.4.0'
    compile 'co.trikita:anvil-design:0.4.0'
```

Do i do something wrong?
I could not find any tutorial or example for the 0.4.0 features

Thanks in advance!

**Comment by amoikevin** [comment]
use this:
import static trikita.anvil.recyclerview.v7.RecyclerViewv7DSL.linearLayoutManager;

**Comment by rubiktubik** [comment]
Thank you!
